import AnimatedText from '@/components/AnimatedText'
import Layout from '@/components/Layout'
import Head from 'next/head'
import React, { useEffect, useRef } from 'react'
import Image from 'next/image'
import profilePic from '../../public/images/profile/fotoPerfil.jpeg' 
import { useInView, useMotionValue, useSpring } from 'framer-motion'
import Skills from '@/components/Skills'
import Experience from '@/components/Experience'
import Education from '@/components/Education'
import TransitionEffect from '@/components/TransitionEffect'


const AnmimatedNumbers = ({value}) => {
  const ref = useRef(null);
  const motionValue = useMotionValue(0);
  const springValue = useSpring(motionValue, {duration: 3000})
  const isInView = useInView(ref);

  useEffect(() => {
    if(isInView){
      motionValue.set(value)
    }
  }, [isInView, value, motionValue])
  
  useEffect(() => {
    springValue.on("change", (latest) => {
      if(ref.current && latest.toFixed(0) <= value){
        ref.current.textContent = latest.toFixed(0)
      }
    })
  }, [springValue, value])

  return <span ref={ref}></span>
}


const about = () => {
  return (
    <>
      <Head>
        <title>Carlos Roque | Acerca de mí</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect/>
      <main className='flex w-full flex-col items-center justify-center dark:text-light'>
        <Layout className='pt-16'>
          <AnimatedText text='Acerca de mí' className='mb-16 lg:!text-7xl sm:!text-6xl xs:!text-4xl sm:mb-8'/>
          <div className='grid w-full grid-cols-8 gap-16 sm:gap-6'>
            <div className='col-span-3 flex flex-col items-start justify-start xl:col-span-4 md:order-2 md:col-span-8'>
              <h2 className='mb-4 text-lg font-bold uppercase text-dark/75 dark:text-light/75'>Biografia</h2>
              <p className='font-medium'>
                Hola, soy Carlos Roque Mallhua, desarrollador web y móvil apasionado por crear soluciones digitales eficientes, innovadoras y centradas en la experiencia del usuario. Con experiencia en tecnologías como React, Next.js, SwiftUI, Kotlin y Flutter, siempre busco optimizar el rendimiento y la usabilidad en cada proyecto en el que trabajo.
              </p>
              <p className='my-4 font-medium'>
                Creo que el desarrollo de software no solo se trata de escribir código, sino de solucionar problemas y diseñar experiencias intuitivas que mejoren la interacción de los usuarios con la tecnología. Me especializo en la depuración, optimización y migración de tecnologías para garantizar productos digitales modernos y escalables.
              </p>
              <p className='font-medium'>
                Ya sea en el desarrollo de un sitio web, una aplicación móvil o cualquier otro producto digital, mi compromiso es brindar soluciones de alta calidad con un enfoque centrado en el usuario. Estoy listo para aportar mis habilidades y pasión a su próximo proyecto.
              </p>
            </div>

            <div className='col-span-3 relative h-max rounded-2xl border-2 border-solid border-dark bg-light p-8 dark:bg-dark dark:border-light xl:col-span-4 md:order-1 md:col-span-8'>
              <div className='absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark dark:bg-light ' />
                <Image src={profilePic} atl='Carlos Roque' className='w-full h-auto rounded-2xl' priority sizes='(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw'/>
            </div>
            <div className='col-span-2 flex flex-col items-end justify-between xl:col-span-8 xl:flex-row xl:items-center md:order-3'>
                <div className='flex flex-col items-end justify-center xl:items-center '>
                  <span className='inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl'>
                    <AnmimatedNumbers value={2}/> +
                  </span>
                  <h2 className='text-xl font-medium capitalize text-dark/75 dark:text-light/75 xl:text-center md:text-lg sm:text-base xs:text-sm'>Empresas colaboradas</h2>
                </div>
                <div className='flex flex-col items-end justify-center xl:items-center'>
                  <span className='inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl'>
                  <AnmimatedNumbers value={5}/> +
                  </span>
                  <h2 className='text-xl font-medium capitalize text-dark/75 dark:text-light/75 xl:text-center md:text-lg sm:text-base xs:text-sm'>Meses de experiencia</h2>
                </div>
                <div className='flex flex-col items-end justify-center xl:items-center'>
                  <span className='inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl'>
                  <AnmimatedNumbers value={5}/> +
                  </span>
                  <h2 className='text-xl font-medium capitalize text-dark/75 dark:text-light/75 xl:text-center md:text-lg sm:text-base xs:text-sm'>Certificaciones</h2>
                </div>
            </div>
          </div>
          <Skills/>
          <Experience/>
          <Education />
        </Layout>
      </main>
    </>
  )
}

export default about
