import AnimatedText from '@/components/AnimatedText'
import Layout from '@/components/Layout'
import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
import profilePic from '../../public/images/profile/fotoPerfil.jpeg' 

const about = () => {
  return (
    <>
      <Head>
        <title>Carlos Roque | About page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex w-full flex-col items-center justify-center'>
        <Layout className='pt-16'>
          <AnimatedText text='About page' className='mb-16'/>
          <div className='grid w-full grid-cols-8 gap-16'>
            <div className='col-span-3 flex flex-col items-start justify-start'>
              <h2 className='mb-4 text-lg font-bold uppercase text-dark/75 '>Biography</h2>
              <p className='font-medium'>
                Hola, soy CodeBucks, desarrollador web y diseñador UI/UX apasionado por crear experiencias digitales bonitas, funcionales y centradas en el usuario. Con 4 años de experiencia en el campo. Siempre estoy buscando nuevas e innovadoras formas de llevar las visiones de mis clientes a la vida.
              </p>
              <p className='my-4 font-medium'>
                Creo que el diseño es algo más que hacer que las cosas se vean bonitas se trata de resolver problemas y crear experiencias intuitivas y agradables para los usuarios.
              </p>
              <p className='font-medium'>
                Ya sea que esté trabajando en un sitio web, una aplicación móvil u otro producto digital, aporto mi compromiso con la excelencia en el diseño y el pensamiento centrado en el usuario a cada proyecto en el que trabajo. Espero tener la oportunidad de aportar mis habilidades y pasión a su próximo proyecto.
              </p>
            </div>

              <div className='col-span-3 relative h-max rounded-2xl border-2 border-solid border-dark bg-light p-8'>
                <Image src={profilePic} atl='Carlos Roque' className='w-full h-auto rounded-2xl'/>

            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}

export default about
