import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import ProfilePic from '../../public/images/profile/developer-pic-4.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import TransitionEffect from '@/components/TransitionEffect'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect/>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light '>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full gap-8 lg:flex-col '>
            <div className='w-1/2 md:w-full'>
              <Image src={ProfilePic} alt="CodeBucks" className='w-full h-auto lg:hidden md:inline-block md:w-full' priority sizes='(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw'/>
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText text="Convertir ideas en soluciones innovadoras con tecnología" className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text=6xl md:!text-5xl sm:!text-3xl'/>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>Como desarrollador  web y móvil, combino creatividad y habilidad técnica para transformar ideas en aplicaciones funcionales y atractivas. Mi experiencia abarca desde React.js hasta Flutter, abarcando tecnologías modernas como SwiftUI, Node.js, NextJS.</p>
            
            <div className='flex items-center self-start mt-2 lg:self-center'>
              <Link href="/cv.pdf" target={"_blank"} className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base' download={true}>CV<LinkArrow className={'w-6 ml-1'}/> 
              </Link>
              {/* <Link href="mailto:carlos.roque@tecsup.edu.pe" target={"_blank"} className='ml-4 text-lg font-medium capitalize text-dark underline'>Contacto</Link> */}
              <Link href="/projects" className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base'>Proyectos</Link>
            </div>
          </div>
        </div>
        </Layout>
        <HireMe/>
      </main>
    </>
  )
}
