import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import ProfilePic from '../../public/images/profile/developer-pic-4.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full '>
            <div className='w-1/2 animate-fadeIn'>
              <Image src={ProfilePic} alt="CodeBucks" className='w-full h-auto'/>
            </div>
            <div className='w-1/2'>
              <h1>
              Convertir la visión en realidad con código y diseño. 
              </h1>
              <p>Como desarrollador full-stack experto, me dedico a convertir ideas en aplicaciones web innovadoras. Explora mis últimos proyectos y artículos, mostrando mi experiencia en React.js y desarrollo web.</p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
