import React from 'react'
import Head from 'next/head'
import Layout from '@/components/Layout'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { GithubIcon, LinkedInIcon } from '@/components/Icons'
import project1 from '../../public/images/projects/PrototipadoCuidatec.png'
import Image from 'next/image'
import { FaReact, FaNodeJs, FaHtml5, FaCss3Alt, FaJsSquare } from 'react-icons/fa';
import { SiFlutter, SiDart, SiFirebase } from 'react-icons/si';


const FeatureProject = ({type, title, summary, img, link, github, icons = []}) => {
  return (
    <article className='w-full flex items-center justify-between rounded-3xl border border-solid border-dark bg-light shadow-2xl p-10'>
      <Link href={link} target='_blank' className='w-1/2 cursor-pointer overflow-hidden rounded-lg '>
        <Image src={img} alt={title} className='w-full h-auto'/>
      </Link>
      <div className='w-1/2 flex flex-col items-start justify-between pl-6'>
        <span className='text-primary font-medium text-xl'>{type}</span>
        <Link href={link} target='_blank' className='hover:underline underline-offset-2'>
          <h2 className='my-2 w-full text-left text-4xl font-bold'>{title}</h2>
        </Link>
        <p className='my-2 font-medium text-dark'>{summary}</p>
        <div className='mt-4 flex flex-row items-center justify-between w-full'>
          <div className='gap-2 flex flex-row items-center'>
          {icons.map((Icon, index) => (
              <Icon key={index} className='w-10 h-10 transform transition-transform duration-300 hover:scale-125 text-primary'/>
            ))}
          </div>
          <div className='w-10'>
            <Link href={github} target='_blank' ><GithubIcon className='transform transition-transform duration-300 hover:scale-125'/></Link>
            {/* <Link href={link} target='_blank' className='ml-4 rounded-lg bg-dark text-light p-2 px-6 text-lg font-semibold'>Visitar Proyecto</Link> */}
          </div>
        </div>
      </div>
    </article>
  )
}


const projects = () => {
  return (
    <>
      <Head>
        <title>Carlos Roque | Proyectos</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='w-full mb-16 flex flex-col items-center justify-center'>
        <Layout className='pt-16'>
          <AnimatedText text='Proyectos' className='mb-16'/>
          <div className='grid grid-cols-12 gap-24'>
            <div className='col-span-12'>
              <FeatureProject img={project1} title='CuidaTec' github='https://github.com/CarlosRoqueM/CuidaTec.git' summary='Cuidatec es una aplicación móvil diseñada para facilitar la conexión entre familias y enfermeras especializadas en el cuidado de personas mayores. El proyecto surge como una respuesta a la creciente necesidad de brindar atención personalizada y profesional a nuestros seres queridos en una etapa crucial de sus vidas.'
              link='/' type='Aplicativo movil' icons={[SiFlutter, SiDart, SiFirebase, FaNodeJs]}/>
            </div>
            <div className='col-span-6'>
              feature projects -1
            </div>
            <div className='col-span-6'>
              feature projects -2
            </div>
            <div className='col-span-12'>
              feature projects
            </div>
            <div className='col-span-6'>
              feature projects -1
            </div>
            <div className='col-span-6'>
              feature projects -2
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}

export default projects
